name: Release plugin version
on: 
  workflow_dispatch:
  push:
    branches: [master, main, beta]

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm clean-install
        env:
          HUSKY: 0
      # TODO: Re-enable after https://github.com/blacksmithgu/obsidian-dataview/issues/2288
      # - name: Audit dependencies
      #   run: npm audit && npm audit signatures
      # - name: Audit code coverage
      #   run: npm run coverage
      - name: Build plugin
        run: npm run build
      - name: Release update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
